version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
cache: src\packages -> **\packages.config
configuration: Release
shallow_clone: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore c:\projects\AzurePlay\src
build:
  publish_wap: true
  publish_azure: true
  verbosity: minimal
deploy:
  provider: AzureCS
  subscription_id: $(sub_id)
  subscription_certificate: $(sub_certificate)
  storage_account_name: azureplayclassicstorage
  storage_access_key: $(storage_access_key)
  service: azureplaycloudservice
  slot: production
  deployment_label: $(appveyor_build_version)
  artifact: AzureCloudService.cspkg
  target_profile: Cloud
  do_not_start_deployment: false
  recreate_deployment: true
